[book]
authors = ["ADI Foundation"]
language = "en"
src = "src"
title = "Airbender Platform"

[output.html]
smart-punctuation = true
git-repository-url = "https://github.com/ADI-Foundation-Labs/ADI-Stack-Airbender-Platform/tree/main/docs"
edit-url-template = "https://github.com/ADI-Foundation-Labs/ADI-Stack-Airbender-Platform/edit/main/docs/{path}"
additional-js = ["js/version-box.js"]
additional-css = ["css/version-box.css"]

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
