[package]
name = "test_program"
version = "0.1.0"
edition = "2021"
authors = ["ADI Foundation"]
homepage = "https://adi.foundation"
repository = "https://github.com/ADI-Foundation-Labs/ADI-Stack-Airbender-Platform/"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync", "zk", "risc-v"]
categories = ["cryptography"]

[dependencies]
airbender = { package = "airbender-sdk", path = "../../../../../crates/airbender-sdk" }
crypto = { package = "airbender-crypto", path = "../../../", features = ["blake2s_tests"]}

[workspace]

[features]
single_round_with_control = ["crypto/single_round_with_control"]
